### ISSUE TITLE
Exception: Array to string conversion in lib/ObjectSerializer.php(264)

### ISSUE THREAD

**Issue by shmaliy** [ExaVault/evapi-php#6]
#0 [internal function]: yii\\base\\ErrorHandler->handleError(8, \'Array to string...\', \'/var/www/html/e...\', 264, Array)
#1 /var/www/html/evapi/lib/ObjectSerializer.php(264): settype(\'Array\', \'string\')
#2 /var/www/html/evapi/lib/ObjectSerializer.php(311): Swagger\\Client\\ObjectSerializer::deserialize(\'Array\', \'string\', NULL)
#3 /var/www/html/evapi/lib/ObjectSerializer.php(245): Swagger\\Client\\ObjectSerializer::deserialize(Object(stdClass), \'\\\\Swagger\\\\Client...\', NULL)
#4 /var/www/html/evapi/lib/ObjectSerializer.php(311): Swagger\\Client\\ObjectSerializer::deserialize(Array, \'\\\\Swagger\\\\Client...\', NULL)
#5 /var/www/html/evapi/lib/Api/FilesAndFoldersApi.php(703): Swagger\\Client\\ObjectSerializer::deserialize(Object(stdClass), \'\\\\Swagger\\\\Client...\', Array)
#6 /var/www/html/evapi/lib/Api/FilesAndFoldersApi.php(627): Swagger\\Client\\Api\\FilesAndFoldersApi->getFoldersWithHttpInfo(\'audoboox-4rklFS...\', \'5b648abbef9357d...\', \'/\')
#7 /var/www/html/backend/components/Exavault.php(64): Swagger\\Client\\Api\\FilesAndFoldersApi->getFolders(\'audoboox-4rklFS...\', \'5b648abbef9357d...\', \'/\')
#8 /var/www/html/console/controllers/MetaController.php(41): backend\\components\\Exavault->folders()
#9 [internal function]: console\\controllers\\MetaController->actionTestFolders()
#10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(151): yii\\base\\InlineAction->runWithParams(Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(91): yii\\base\\Controller->runAction(\'test-folders\', Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(455): yii\\console\\Controller->runAction(\'test-folders\', Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Application.php(167): yii\\base\\Module->runAction(\'meta/test-folde...\', Array)
#15 /var/www/html/vendor/yiisoft/yii2/console/Application.php(143): yii\\console\\Application->runAction(\'meta/test-folde...\', Array)
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(375): yii\\console\\Application->handleRequest(Object(yii\\console\\Request))
#17 /var/www/html/yii.php(27): yii\\base\\Application->run()

If I'm print data above 264 line, it shows me tree of files and folders objects. But after 264 line it throws an exception

**Comment by shmaliy** [comment]
Anybody here?

**Comment by ksaveras** [comment]
+1
